export enum AuditAction {
  CREATED = "CREATED",
  UPDATED = "UPDATED",
  DELETED = "DELETED",
  WAIVED = "WAIVED",
  PENALTY_APPLIED = "PENALTY_APPLIED",
  CHEQUE_CLEARED = "CHEQUE_CLEARED",
  CHEQUE_BOUNCED = "CHEQUE_BOUNCED",
  PAYMENT_RECORDED = "PAYMENT_RECORDED",
  PAYMENT_REVERSED = "PAYMENT_REVERSED",
  BULK_PAYMENT = "BULK_PAYMENT",
  REMINDER_SENT = "REMINDER_SENT",
  SUSPICIOUS_WEBHOOK_ATTEMPT = "SUSPICIOUS_WEBHOOK_ATTEMPT",
  REFUND_PROCESSED = "REFUND_PROCESSED",
}

export enum Role {
  ADMIN = "ADMIN",
  CASHIER = "CASHIER",
}

export enum StudentStatus {
  ACTIVE = "ACTIVE",
  TRANSFERRED = "TRANSFERRED",
  ALUMNI = "ALUMNI",
}

export enum LedgerStatus {
  PENDING = "PENDING",
  PARTIAL = "PARTIAL",
  PAID = "PAID",
  OVERDUE = "OVERDUE",
}

export enum PaymentMethod {
  UPI = "UPI",
  CASH = "CASH",
  CHEQUE = "CHEQUE",
}

export enum TransactionStatus {
  PENDING = "PENDING",
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
  PENDING_CLEARANCE = "PENDING_CLEARANCE",
  CLEARED = "CLEARED",
  PARTIALLY_CLEARED = "PARTIALLY_CLEARED",
  BOUNCED = "BOUNCED",
}
